name: first

on:
  pull_request:
    branches: ['main']

jobs:
  read_description:
    if: ${{ github.event_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install packages
        run: npm install @actions/core @actions/github
      - name: Check for linked ticket
        uses: ./scripts/check-description
        with:
          pull_request: ${{ github.event.pull_request_comment }}


