name: Linked TAPP Ticket
on:
  pull_request:
    types: ['edited', 'reopened', 'opened', 'synchronize']
    branches: ['main']
jobs:
  read_description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install packages
        run: cd scripts && npm install
      - name: Check for linked ticket
        uses: ./scripts/check-description